v1:
	$(MAKE) -C out v1

v21:
	$(MAKE) -C out v21

v22:
	$(MAKE) -C out v22

v31:
	$(MAKE) -C out v31
	
v32:
	$(MAKE) -C out v32

run:
	$(MAKE) -C scripts run

compile:
	$(MAKE) -C out compile

clean:
	$(MAKE) -C out clean
